#! /usr/bin/env node

/**
 * This tool is to initialize the application by
 * installing the required packages that defined
 * in configuration,  groups them into workspace.
 *
 * @copryright 2022
 */
const { cpSync } = require('fs');
const { resolve } = require('path');
const { touchFile, absoluteToRelative } = require('./utils/file');
const { validateApp } = require('./utils/app');
const tree = require('./utils/tree');

const templatePath = resolve('./packages/api/template');
const { scope, app, sourcePath, appPath } = validateApp({
  template: templatePath,
});

function touchFiles() {
  const files = [
    'Dockerfile',
    'env.example',
    'package.json',
  ];
  files.forEach((file) => touchFile(appPath(file), (content) => {
    console.log(`[INFO] Updating file content [${file}]...`);
    return content
      .replaceAll('{SCOPE_NAME}', scope)
      .replaceAll('{APP_NAME}', app);
  }));
}

function init() {
  console.log(`[INFO] Copying template files into ${appPath()}...`);
  cpSync(sourcePath, appPath(), {
    recursive: true,
    dereference: false,
    verbatimSymlinks: false,
  });
  absoluteToRelative(appPath());
  touchFiles();
}

init();
console.log('[INFO] Code-base initialization is done...');
tree(appPath());
